### ISSUE TITLE
同步出错

### ISSUE THREAD

**Issue by elwinhoo** [alibaba/RedisShake#102]
阿里云redis实例之间的同步出如下错误：
版本：2.8->4.0
2019/06/18 11:24:09 [INFO] routine[0] starts syncing data from 192.168.6.2:6379 to [r-wz914ed7bd8be154506.redis.rds.aliyuncs.com:6379] wit
h http[9321]2019/06/18 11:24:09 [PANIC] invalid sync response, rsp = '-ERR command sync not support for normal user
'
[stack]: 
    0   /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:190
            redis-shake/common.waitRdbDump.func1

**Comment by ysnows** [comment]
咋解决的？

**Comment by vinllen** [comment]
云上2.8版本不支持复制权限，4.0主从支持的，控制台可以申请。
