### ISSUE TITLE
filter 规则不生效

### ISSUE THREAD

**Issue by navyaijm2017** [alibaba/RedisShake#108]
源版本：codis-server 3.2.4
目标版本： redis_version:5.0.2
share版本：improve-1.6.9,1737b9045681eb923830add7743606075c71b748,go1.10.3,2019-06-24_16:14:53
过来策略：
filter.db = 0
filter.key =mms*;aisp*

结果：
目标redis一个key都没有同步过去

**Comment by vinllen** [comment]
filter.key =mms*;aisp*
--------------
这个存在问题，前缀匹配：`filter.key = mms;aisp`
