### ISSUE TITLE
restore command error key:xxxxxxxxxx  err:ECONNTIMEOUT

### ISSUE THREAD

**Issue by oracle1521** [alibaba/RedisShake#110]
使用redis-shake迁移集群时报如下错误：
```
2019/07/02 16:13:57 [PANIC] restore command error key:xxxxxxxxxx  err:ECONNTIMEOUT
[error]: ECONNTIMEOUT
[stack]: 
    1   /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:805
            redis-shake/common.RestoreRdbEntry
    0   /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:441
            redis-shake.(*dbSyncer).syncRDBFile.func1.1
        ... ...
```
redis版本：4.0.2

**Comment by vinllen** [comment]
`ECONNTIMEOUT`这个错误第一次见，目的端是什么redis的版本？开源的cluster？主从版？还是某个云厂商的？

**Comment by oracle1521** [comment]
用的都是开源版本，源端和目标端均为 3分片集群、每个分片1从

源端信息
`
source> info server
# Server
redis_version:4.0.2
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:95e49a88b35a1f90
redis_mode:cluster
os:Linux 3.10.0-693.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.8.5
process_id:3233
run_id:bf16ec8cbd5d61be3be4ce3988f12240bdb34a75
tcp_port:7000
uptime_in_seconds:8243004
uptime_in_days:95
hz:10
lru_clock:1834395
`

目标端信息
`
> info server
# Server
redis_version:4.0.2
redis_git_sha1:00000000
redis_git_dirty:0
redis_build_id:1468507e2527e0f2
redis_mode:cluster
os:Linux 3.10.0-957.21.3.el7.x86_64 x86_64
arch_bits:64
multiplexing_api:epoll
atomicvar_api:atomic-builtin
gcc_version:4.8.5
process_id:22846
run_id:d715ff268300a8f4345e818f530c5fb8d5e11379
tcp_port:7000
uptime_in_seconds:78966
uptime_in_days:0
hz:10
lru_clock:1834442
`

**Comment by vinllen** [comment]
微信上加我一下，看起来是目的端断连了，辅助调试一下

**Comment by vinllen** [comment]
![image](https://user-images.githubusercontent.com/6987398/60562045-7c6ad500-9d88-11e9-846a-adf9567f7169.png)
修改后用户反馈的进一步报错信息，网络不可达问题。

**Comment by oracle1521** [comment]
跨机房迁移（网路不互通）情况下，如果集群通信配置的是内网ip，即使目标主机上配置公网ip能连接访问，也是不能迁移的。 @vinllen 说是driver的问题。
谢谢 @vinllen 的支持~~
