### ISSUE TITLE
metric接口的 Pull和Push的数量对不上

### ISSUE THREAD

**Issue by navyaijm2017** [alibaba/RedisShake#117]
配置了过滤前缀key同步，通过metric接口查看，发现Pull和Push的数量对不上

**Comment by navyaijm2017** [comment]
![image](https://user-images.githubusercontent.com/29217326/60695527-8f121500-9f14-11e9-861d-ae26c8fb2a92.png)

**Comment by vinllen** [comment]
bypass的统计不对 加上了。
目前这些都是增量的数据，考虑加上全量的统计数据

**Comment by navyaijm2017** [comment]
> bypass的统计不对 加上了。
> 目前这些都是增量的数据，考虑加上全量的统计数据

已验证，非常感谢
