### ISSUE TITLE
Can RedisShake skip sync all data when start but continue do "forwardCommands" ?

### ISSUE THREAD

**Issue by bas80836255** [alibaba/RedisShake#123]
In this case my source redis have key about 1 Million and I have start redis shake with sync command. It takes a while for sync data.
Later redisshake was terminated and i want to start redisshake again then redisshake have sync all key in source redis again and print log all the same key have sync 

eg. 

```
2019/07/12 17:35:40 [INFO] warning, rewrite key: {$key}
2019/07/12 17:35:40 [INFO] warning, rewrite key: {$key}
....
...
...
(key per line. if i have 1 million key it will print 1 million line )
```
I want to  skip sync all data and do "fowardCommands" only.

What is your recommend way?

pls forgive my english skill, thank you very much

**Comment by vinllen** [comment]
What you want is skip RDB sync and do increase sync only, right? The answer is no.
Why do you want to skip RDB sync? This may make data lost.

**Comment by bas80836255** [comment]
My redis have many key.

I use supervisor for monitor and control redis-shake.

When redis-shake terminated and I restart it immediately . Redis-shake take a time for RDB sync before increase sync. I don't want to waste time in RDB sync.

However I forgot about data lost.

Thank for answer my question.
