### ISSUE TITLE
希望加入Sentinel的支持

### ISSUE THREAD

**Issue by wangyiyang** [alibaba/RedisShake#17]
希望能够加入Sentinel的支持，毕竟单节点的Redis在生产环境是很少用的，希望RedisShake能够订阅Sentinel，当Sentinel发生角色切换的时候，能够切换自己的源（期望是某个从节点）

**Comment by vinllen** [comment]
v1.6.1版本已经支持从sentinel中获取地址，failover逻辑暂未处理
