### ISSUE TITLE
断点续传功能支持

### ISSUE THREAD

**Issue by vinllen** [alibaba/RedisShake#18]
考虑支持断点续传功能，由于4.0及以上版本推出的psync2，支持主备切换时候维持master的replid信息，同步replid(4.0以下称runid)+offset信息可以实现断点续传的目的。
当redis-shake断开连接，重新连接后，可以根据这2个信息进行重新拉取，主备切换也能支持。
psync2参考redis主从同步，replication.c/masterTryPartialResynchronization函数。
redis-shake层面本身进行拉取持久化offset位点操作，但目前目的端写入是异步状态，以及源端offset如何获取。这样重启后可以恢复位点，psync进行拉取。
目前该需求的开发支持在讨论中。

**Comment by wangyiyang** [comment]
+1

**Comment by ceshihao** [comment]
这个功能是否能解决如下情况？

从redis A同步到B。对于一个List的key K，源端A会一直有写入push，目标B也会有一些写入push/pop。
目前的版本，一旦redis-shake因某种原因重启，理论上会重新同步A中的key，丢失掉B的写入。
如果支持此续传功能，能否保持B的修改？

**Comment by vinllen** [comment]
可以。
目前重启会导致B的丢失，是因为全量同步restore覆盖目的端导致的。如果断点续传，增量写入不会发生覆盖。

**Comment by ceshihao** [comment]
这个功能在近期的计划中吗？

**Comment by vinllen** [comment]
是的，还在计划中，方案暂未敲定。

**Comment by vinllen** [comment]
进入排期，1.8版本计划支持。

**Comment by wangyiyang** [comment]
是记录offset做续传还是模拟了最新的psync

**Comment by vinllen** [comment]
续传是根据psync来的，也是需要记录源端的offset，这个后面会有设计文档的输出

**Comment by vinllen** [comment]
1.7版本发布断点续传非稳定版本

**Comment by vinllen** [comment]
2.0已经支持断点续传，请查看wiki文档

**Comment by 52hzbobo** [comment]
RedisShake 4.x支持断点续传吗

**Comment by Phoebus888** [comment]
RedisShake 4.x支持断点续传吗

**Comment by suxb201** [comment]
@52hzbobo @Phoebus888 不支持，无计划支持
