### ISSUE TITLE
redis-shake同步数据过程中异常: i/o timeout

### ISSUE THREAD

**Issue by yanan0628** [alibaba/RedisShake#192]
当前有个100g+集群 从Redis3.0.7同步数据到5.0.6版本 报错，多次同步尝试出现以下异常。源/目标节点 redis都是通，请问这个可能是什么影响的？
异常1：
...
2019/11/21 17:37:41 [INFO] warning, rewrite key: ugc.comment:comment.timestamp.list@vp_96653533
2019/11/21 17:37:41 [PANIC] restore command response = 'ECONNTIMEOUT: dial tcp 10.11.*.*:6382: i/o timeout', should be 'OK'
[stack]:
1 /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:847
redis-shake/common.RestoreRdbEntry
异常2：
...
2019/11/21 17:05:21 [INFO] dbSyncer[58] total=304813739 - 90056790 [ 29%] entry=691456
2019/11/21 17:05:21 [PANIC] dbSyncer[86] Event:NetErrorWhileFlush Id:redis-shake-20191121164934 Error:dial tcp 10.11.*.*:6384: i/o timeout
[stack]:
0 /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:696
redis-shake.(*dbSyncer).syncCommand.func4
... ...

**Comment by vinllen** [comment]
回复一下几个问题：
1. 问题是否稳定复现
2. 目的端redis是否有异常log
打开Debug日志再重试一下

**Comment by sofire** [comment]
遇到类似的问题，调试发现 是因为 目标节点的 key已经存在，conn被关闭。
导致 不停的关闭、打开连接。
加了个判断就好了。

src/vendor/github.com/vinllen/redis-go-cluster/node.go
`
func (node *redisNode) do

	reply, err := conn.receive()
	if err != nil {
		if strings.Contains(err.Error(), "Target key name is busy") ||
			strings.Contains(err.Error(), "BUSYKEY Target key name already exists") {

		} else {
			conn.shutdown()
			return nil, err
		}
	}
`

**Comment by sofire** [comment]
conn.receive()  有返回 错误信息，是不是 可以不用 shutdown 呢？

**Comment by vinllen** [comment]
返回出错需要直接退出，否则数据可能会出现不一致。

**Comment by whh881114** [comment]
我也碰到这样的错误了，我flushall目标redis-cluster就没有这样的错误了：[PANIC] restore command response = 'ECONNTIMEOUT: dial tcp 10.11..:6382: i/o timeout', should be 'OK'；不过用另外的一个问题，为什么在同步时，源集群一直在扫这样的信息（从凌晨00:30一直持续到现在），像是没有开始同步，但是我在目标集群可以看到有数据生成。

2019/12/06 09:32:06 [INFO] dbSyncer[5] total = 989.281MB -    551.114MB [ 55%]  entry=3439295     
2019/12/06 09:32:06 [INFO] dbSyncer[3] total = 935.173MB -    350.610MB [ 37%]  entry=2469905     
2019/12/06 09:32:07 [INFO] dbSyncer[1] total = 895.411MB -    455.511MB [ 50%]  entry=2938964     
2019/12/06 09:32:07 [INFO] dbSyncer[2] total = 976.628MB -    424.492MB [ 43%]  entry=2911502     
2019/12/06 09:32:07 [INFO] dbSyncer[0] total = 942.665MB -    392.743MB [ 41%]  entry=2746916     
2019/12/06 09:32:07 [INFO] dbSyncer[4] total = 1.309GB -    806.074MB [ 60%]  entry=3420815

**Comment by vinllen** [comment]
用这个打一下内部堆栈看一下，可以钉钉上私聊我一下
curl http://127.0.0.1:{system_port}/debug/pprof/goroutine?debug=2

**Comment by whh881114** [comment]
我清空过目标redis集群数据，也发现这个错误。

2019/12/06 23:59:50 [PANIC] restore command response = 'ECONNTIMEOUT: dial tcp 10.8..x.x:11006: connect: cannot assign requested address', should be 'OK'
[stack]: 
    1   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/common/utils.go:848
            redis-shake/common.RestoreRdbEntry
    0   /Users/vinllen-ali/code/redis-shake-inner/redis-shake/src/redis-shake/sync.go:447
            redis-shake.(*dbSyncer).syncRDBFile.func1.1
        ... ...

**Comment by vinllen** [comment]
这个在1.6.23里面是否还会复现？

**Comment by whh881114** [comment]
是的，一直复现；机器部署环境五主五从，但只有五台主机，每台主机继扮演master扮演slave。不过，像另外的三主三从（三台主机搭建）就没有问题，感觉还是和key有关系。

**Comment by vinllen** [comment]
钉钉私聊我下

**Comment by whh881114** [comment]
已加入 shake数据库同步官方群

**Comment by vinllen** [comment]
```
2019/12/07 13:27:21 [PANIC] restore command response = 'ECONNTIMEOUT: dial tcp 10.8.60.133:1000: connect: cannot assign requested address', should be 'OK'
```
这个是文件端口耗尽了，并不是timeout，现象并不一致。

**Comment by vinllen** [comment]
@yanan0628 1.6.23版本问题是否还存在

**Comment by vinllen** [comment]
用户反馈，集群版同步，source.rdb.parallel配置设置>3必现，前后redis本身无异常，从日志看来超时之前也没有卡住一定的时间，看起来是驱动层面的bug，但抛出的错误的确是tcp层面的timeout。
```
2019/12/11 21:15:59 [INFO] dbSyncer[1] total = 237.257MB -     14.284MB [  6%]  entry=36027
2019/12/11 21:15:59 [INFO] dbSyncer[3] total = 240.827MB -     12.714MB [  5%]  entry=36644
2019/12/11 21:16:00 [INFO] dbSyncer[4] total = 244.065MB -     13.180MB [  5%]  entry=35189
2019/12/11 21:16:00 [INFO] dbSyncer[0] total = 246.489MB -     13.169MB [  5%]  entry=36104
2019/12/11 21:16:00 [INFO] dbSyncer[5] total = 274.430MB -     14.182MB [  5%]  entry=32931
2019/12/11 21:16:00 [INFO] dbSyncer[7] total = 275.705MB -     11.510MB [  4%]  entry=35010
2019/12/11 21:16:00 [INFO] dbSyncer[6] total = 248.780MB -     15.515MB [  6%]  entry=36434
2019/12/11 21:16:00 [INFO] dbSyncer[2] total = 247.290MB -     15.724MB [  6%]  entry=34716
2019/12/11 21:16:00 [INFO] dbSyncer[1] total = 237.257MB -     14.284MB [  6%]  entry=36027
2019/12/11 21:16:00 [INFO] dbSyncer[3] total = 240.827MB -     12.714MB [  5%]  entry=36644
2019/12/11 21:16:01 [INFO] dbSyncer[4] total = 244.065MB -     13.180MB [  5%]  entry=35189
2019/12/11 21:16:01 [INFO] dbSyncer[0] total = 246.489MB -     13.169MB [  5%]  entry=36104
2019/12/11 21:16:01 [INFO] dbSyncer[5] total = 274.430MB -     14.182MB [  5%]  entry=32931
2019/12/11 21:16:01 [INFO] dbSyncer[7] total = 275.705MB -     11.510MB [  4%]  entry=35010
2019/12/11 21:16:01 [INFO] dbSyncer[6] total = 248.780MB -     15.515MB [  6%]  entry=36434
2019/12/11 21:16:01 [INFO] dbSyncer[2] total = 247.290MB -     15.724MB [  6%]  entry=34716
2019/12/11 21:16:01 [PANIC] restore command response = 'ECONNTIMEOUT: dial tcp 10.0.110.159:6318: connect: connection timed out', should be 'OK'
[stack]:
    1   /opt/RedisShake/src/redis-shake/common/utils.go:848
            redis-shake/common.RestoreRdbEntry
    0   /opt/RedisShake/src/redis-shake/sync.go:447
            redis-shake.(*dbSyncer).syncRDBFile.func1.1
        ... ...
2019/12/11 21:16:01 [PANIC] restore command response = 'ECONNTIMEOUT: dial tcp 10.0.110.160:6308: connect: connection timed out', should be 'OK'
[stack]:
    1   /opt/RedisShake/src/redis-shake/common/utils.go:848
            redis-shake/common.RestoreRdbEntry
    0   /opt/RedisShake/src/redis-shake/sync.go:447
            redis-shake.(*dbSyncer).syncRDBFile.func1.1
        ... ...
```

**Comment by sofire** [comment]
> 返回出错需要直接退出，否则数据可能会出现不一致。

至少 目标key 存在的错误，不需要断开连接吧。

**Comment by vinllen** [comment]
目标key存在，配置文件置rewrite=true就可以，会直接覆盖，不会退出，不置的话会退出。

**Comment by sofire** [comment]
不是 程序退出，是conn会shutdown。 具体代码 在上面 有给出。

**Comment by yuan-make** [comment]
16.23 版本还是会复现

**Comment by yuan-make** [comment]
Version:1.6.23
parallel = 3

即使配置rewrite=true 也是一样的 出现  
`
2019/12/15 23:06:38  [PANIC] restore command response = 'ECONNTIMEOUT: dial tcp 10.x.x:6379: connect: cannot assign requested address', should be '`OK'

netstat  出现大量timewait

pprof 看到大量 goroutine 去 getConn()，建立连接

**Comment by vinllen** [comment]
@yuan-make 目前跟驱动层面对接配置有个地方不太合理，会导致连接大连断开重连，从而进一步引发端口耗尽，下一步会修复。

**Comment by vinllen** [comment]
@yanan0628 问题还存在的话，钉钉上私聊我一下

**Comment by yuan-make** [comment]
> @yuan-make 目前跟驱动层面对接配置有个地方不太合理，会导致连接大连断开重连，从而进一步引发端口耗尽，下一步会修复。

哪个参数呢，keep_alive?

**Comment by vinllen** [comment]
@yuan-make 新版本最近会release，着急的话可以钉钉私聊我 给你个版本

**Comment by vinllen** [comment]
请试一下1.6.24版本

**Comment by vinllen** [comment]
问题先行关闭，如果还存在问题请重新打开该问题。
