### ISSUE TITLE
某些情况下，同步过程中丢失数据

### ISSUE THREAD

**Issue by cedarwu** [alibaba/RedisShake#27]
RedisShake版本：release-v1.2.2-20190403
源redis版本：3.2.8
目的redis版本：4.0.10 cluster
配置：仅增大了 parallel 参数，其余参数均为默认参数
现象：同步过程中，无错误提示，同步完成之后，保持同步进程继续运行。
统计两端key总数，发现目的redis的key数量约为源redis的90%。
使用redis-full-check默认参数进行检查，报错：https://github.com/alibaba/RedisFullCheck/issues/36
使用 redis-full-check -m 3 进行检查，发现两端一致，即工具认为key是一致的。

从调试信息中找到了两端不一致的key：uc_basic_data_2852157937_1_28521579370000000000000000000010

源redis：
\> type uc_basic_data_2852157937_1_28521579370000000000000000000010
hash
\> ttl uc_basic_data_2852157937_1_28521579370000000000000000000010
(integer) 596453

目的redis：
\> type uc_basic_data_2852157937_1_28521579370000000000000000000010
none
\> ttl uc_basic_data_2852157937_1_28521579370000000000000000000010
(integer) -2

**Comment by vinllen** [comment]
调用最新的full check看下，然后给出输出，看日志没有什么异常，是不是这个key是刚写入的。

**Comment by vinllen** [comment]
另外，源端是集群的话，迁移期间不能有move slot操作

**Comment by cedarwu** [comment]
使用最新redis full check (bugfix-1.2.3,5d4ea3cef46a06cc01d8b0df8cd10e01f313946f)，发现确实存在不一致的key，且不一致的都是 hash类型。

**Comment by chemaoxian** [comment]
同步后check出来 发现uc_basic_data_* 相关的key 没有同步成功， 源集群存在该key 目标集群不存在该key

**Comment by vinllen** [comment]
uc_basic_data_开头的key有什么特点吗？shake不会自动过滤，确定没有move slot操作吗？

**Comment by cedarwu** [comment]
我补充了key的内容，看起来也没什么特别的地方，确定没有move slot

**Comment by vinllen** [comment]
@kingpeterpaule 盼总看看这个问题有啥思路吗？

**Comment by vinllen** [comment]
@cedarwu 丢失也是通过info看的？1300w丢了100w，数据的增长率怎么样？

**Comment by cedarwu** [comment]
> @cedarwu 丢失也是通过info看的？1300w丢了100w，数据的增长率怎么样？目前源库的内存压力怎么样，是不是触发了淘汰策略。

是的，keys总数是info信息里的。
今天定位出差100w的问题了，主要是过期的key没有清理导致的，全量scan之后，清理了所有过期的key，key数量已经吻合。
现在主要的问题就是丢失的那3个key了，这3个key看起来是确确实实丢掉了。同步脚本一直保持运行着，源集群存在，目标集群不存在，可以一直复现。

**Comment by vinllen** [comment]
scan本身是会触发淘汰的。丢失的3个key复现都是这3个吗？这个key目前看起来没啥特别的

**Comment by cedarwu** [comment]
这3个key确实没看出任何特别之处。我这里说的复现是因为这3个key的过期时间还很长，即使同步脚本一直开着，也随时可以验证3个key丢失。
后面没有再次尝试了，因为业务方说这3个key不重要，就算不存在也会重新去db取，没关系，也就没有继续定位了。

**Comment by vinllen** [comment]
先记录一下bug吧，目前的确看不出来问题。

**Comment by suxb201** [comment]
这个问题时间太久了，不会有什么进展，可能已经被期间的某个 bugfix 修复了。
如果依旧有问题再新开 Issue 吧，我先关掉此 issue。
