### ISSUE TITLE
panic: CROSSSLOT Keys in request don't hash to the same slot

### ISSUE THREAD

**Issue by cedarwu** [alibaba/RedisShake#34]
版本：bugfix-1.2.1,f04283013e034acf33bee92ebf836aeb8757f5b2,go1.10.3,2019-03-27_20:11:26
同步源：redis 3.2.8 （codis集群中的slave实例）
同步目标：redis 4.0.10（cluster）
配置：
parallel = 1024
source.version = 7
target.version = 7
big_key_threshold = 52428800

rdb同步完成后，增量同步开始时突然panic：
2019/04/16 17:21:16 [INFO] restore big zset key pgg_user_cash_account_pggsign score 9781932760 member 14681071
2019/04/16 17:21:16 [INFO] restore big zset key pgg_user_cash_account_pggsign score 14625880623 member 133930417
2019/04/16 17:21:16 [INFO] restore big zset key pgg_user_cash_account_pggsign score 16749642548 member 4970085
2019/04/16 17:21:16 [INFO] total=1063796856 -   1063796856 [100%]  entry=1160052
2019/04/16 17:21:16 [INFO] sync rdb done
2019/04/16 17:21:16 [INFO] Event:IncrSyncStart  Id:redis_shake_3
2019/04/16 17:21:16 [PANIC] Event:ErrorReply    Id:redis_shake_3        Command: [unknown]      Error: CROSSSLOT Keys in request don't hash to the same slot
[stack]:
    0   /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:408
            redis-shake.(*CmdSync).SyncCommand.func2
        ... ...

**Comment by vinllen** [comment]
目的是集群版，不过你们这个目的redis没有proxy吗？看起来像是开源的集群版。
参考一下[这个](https://stackoverflow.com/questions/38042629/redis-cross-slot-error)。这个是因为操作了多key，而多key分布在不同的结点上。

**Comment by cedarwu** [comment]
请问下这里是指有lua脚本设计多个key吗？

**Comment by vinllen** [comment]
lua脚本操作的key必须分布在一个slot里面，redis自身也有很多操作多key的命令。
可以通过打tag的方式把key挪到一个slot里面。

**Comment by cedarwu** [comment]
这个在redis shake同步过程中应该如何操作呢？有相关的配置吗？
之前业务方在用codis时，使用hashtag把lua脚本需要操作的多个key hash到了同一个slot，用redis shake迁移之后，这个hash关系会保留吗？

**Comment by vinllen** [comment]
会保留
