### ISSUE TITLE
同步出错

### ISSUE THREAD

**Issue by nosqldb** [alibaba/RedisShake#37]
redis 2.8 到5.0
2019/04/19 20:24:45 [WARN] Event:GetFakeSlaveOffsetFail	Id:redis-shake	Warn:OffsetNotFoundInInfo
2019/04/19 20:24:45 [INFO] sync:  +forward=825    +nbypass=0      +nbytes=0
2019/04/19 20:24:46 [INFO] sync:  +forward=748    +nbypass=0      +nbytes=0
2019/04/19 20:24:47 [INFO] sync:  +forward=641    +nbypass=0      +nbytes=0
2019/04/19 20:24:48 [INFO] sync:  +forward=688    +nbypass=0      +nbytes=0
2019/04/19 20:24:49 [INFO] sync:  +forward=678    +nbypass=0      +nbytes=0
2019/04/19 20:24:50 [INFO] sync:  +forward=598    +nbypass=0      +nbytes=0
2019/04/19 20:24:51 [INFO] sync:  +forward=689    +nbypass=0      +nbytes=0
2019/04/19 20:24:52 [INFO] sync:  +forward=846    +nbypass=0      +nbytes=0
2019/04/19 20:24:53 [INFO] sync:  +forward=698    +nbypass=0      +nbytes=0
2019/04/19 20:24:54 [INFO] sync:  +forward=749    +nbypass=0      +nbytes=0
2019/04/19 20:24:55 [WARN] Event:GetFakeSlaveOffsetFail	Id:redis-shake	Warn:OffsetNotFoundInInfo
2019/04/19 20:24:55 [INFO] sync:  +forward=693    +nbypass=0      +nbytes=0
2019/04/19 20:24:56 [INFO] sync:  +forward=854    +nbypass=0      +nbytes=0
2019/04/19 20:24:57 [INFO] sync:  +forward=700    +nbypass=0      +nbytes=0
2019/04/19 20:24:58 [INFO] sync:  +forward=676    +nbypass=0      +nbytes=0
2019/04/19 20:24:59 [INFO] sync:  +forward=627    +nbypass=0      +nbytes=0
2019/04/19 20:25:00 [INFO] sync:  +forward=781    +nbypass=0      +nbytes=0
2019/04/19 20:25:01 [INFO] sync:  +forward=673    +nbypass=0      +nbytes=0
2019/04/19 20:25:02 [PANIC] Event:ErrorReply	Id:redis-shake	Command: [unknown]	Error: MISCONF Redis is configured to save RDB snapshots, but it is currently not able to persist on disk. Commands that may modify the data set are disabled, because this instance is configured to report errors during writes if RDB snapshotting fails (stop-writes-on-bgsave-error option). Please check the Redis logs for details about the RDB error.
[stack]: 
    0   /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:415
            redis-shake.(*CmdSync).SyncCommand.func2
        ... ...

**Comment by vinllen** [comment]
目的端快照被关闭导致不能持久化了，开启一下：
`config set stop-writes-on-bgsave-error no`

**Comment by nosqldb** [comment]
thks,另外这个GetFakeSlaveOffsetFail  warning，在master看不到offset

**Comment by vinllen** [comment]
这个应该是源端info Replication消息中拿不到对应shake的offset信息。在配置文件中启用一下psync应该可以。
