### ISSUE TITLE
redis-shake 5.0 stream大key支持

### ISSUE THREAD

**Issue by vinllen** [alibaba/RedisShake#4]
目前，对于stream类型目前统一restore处理，这对于stream比较小的情况没有问题，但是stream如果value过大，将可能导致以下2个风险：

1. 目的端redis有限流策略将会引发限流
2. 目的端redis由于load需要消耗内存，有引发oom的风险。
3. 超过700MB大小直接restore失败

后续考虑进行优化拆分，不用restore处理，xrange解析源端的拉取命令，挨个xadd写入目的端。对于group consumer类型，还需要适配PEL队列。
这个处理有点繁琐，暂时先搁置。

**Comment by suxb201** [comment]
finished!
