### ISSUE TITLE
迁移过程报oom，但是服务器内存只使用了10%左右

### ISSUE THREAD

**Issue by wwwwwwchun** [alibaba/RedisShake#45]
迁移redis中，报oom错误，但是整个过程中服务器内存使用量一直在250M左右，服务器内存为16GB，详细报错日志如下：
2019/04/26 18:14:44 [INFO] total=2745316203 -     61479452 [  2%]  entry=308680      
2019/04/26 18:14:45 [INFO] total=2745316203 -     61870915 [  2%]  entry=310614      
2019/04/26 18:14:46 [PANIC] parse rdb entry error, if the err is :EOF, please check that if the src db log has client outout buffer oom, if so set output buffer larger.
[error]: EOF
    10  /data/RedisShake-develop/src/pkg/rdb/reader.go:87
            pkg/rdb.(*rdbReader).Read
    9   /data/go/src/io/io.go:535
            io.(*teeReader).Read
    8   /data/RedisShake-develop/src/pkg/rdb/reader.go:85
            pkg/rdb.(*rdbReader).Read
    7   /data/go/src/io/io.go:310
            io.ReadAtLeast
    6   /data/go/src/io/io.go:329
            io.ReadFull
    5   /data/RedisShake-develop/src/pkg/rdb/reader.go:407
            pkg/rdb.(*rdbReader).readFull
    4   /data/RedisShake-develop/src/pkg/rdb/reader.go:413
            pkg/rdb.(*rdbReader).ReadBytes
    3   /data/RedisShake-develop/src/pkg/rdb/reader.go:324
            pkg/rdb.(*rdbReader).ReadString
    2   /data/RedisShake-develop/src/pkg/rdb/reader.go:117
            pkg/rdb.(*rdbReader).readObjectValue
    1   /data/RedisShake-develop/src/pkg/rdb/loader.go:170
            pkg/rdb.(*Loader).NextBinEntry
    0   /data/RedisShake-develop/src/redis-shake/common/utils.go:772
            redis-shake/common.NewRDBLoader.func1
        ... ...
[stack]: 
    0   /data/RedisShake-develop/src/redis-shake/common/utils.go:773
            redis-shake/common.NewRDBLoader.func1
        ... ...

**Comment by vinllen** [comment]
参考下这个，这个oom不是redis oom了，而是Output buffer不够用
https://github.com/alibaba/RedisShake/wiki/FAQ#q-how-to-solve-the-panic-parse-rdb-entry-error-if-the-err-is-eof-please-check-that-if-the-src-db-log-has-client-outout-buffer-oom-if-so-set-output-buffer-larger-error

**Comment by wwwwwwchun** [comment]
我们把进程数调大后，提示源端连接不上

**Comment by vinllen** [comment]
那可能是源端redis的连接数打满了，或者被限流了。

**Comment by wwwwwwchun** [comment]
我们源端的redis是10000的连接数，这个我们看了一下，连接数没有占满，
现在是每次到90%就出现oom的错误，错误信息如下：
2019/04/27 12:27:18 [INFO] total=2102270930 -   1903242719 [ 90%]  entry=3754749     
2019/04/27 12:27:18 [INFO] restore big key adminUserInfo Value Length 16777239 type 4
2019/04/27 12:27:18 [INFO] restore big hash key adminUserInfo field count 4072
2019/04/27 12:27:19 [PANIC] flush command to redis failed
[error]: OOM command not allowed when used memory > 'maxmemory'.
[stack]: 
    3   /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:292
            redis-shake/common.flushAndCheckReply
    2   /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:624
            redis-shake/common.restoreBigRdbEntry
    1   /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:688
            redis-shake/common.RestoreRdbEntry
    0   /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:316
            redis-shake.(*CmdSync).SyncRDBFile.func1.1
        ... ...

**Comment by vinllen** [comment]
源端内存不够用了，参考一下：https://ma.ttias.be/redis-oom-command-not-allowed-used-memory-maxmemory/

**Comment by wwwwwwchun** [comment]
问题好像找到了，我们有一个大key，key类型是hash类型，大小是2G，每次全量同步到这个key的时候出现oom问题。

**Comment by vinllen** [comment]
redis-shake支持对大key的分entry处理，配置文件中有阈值的大小，如果超过了这个大小，会分批写入这个key，默认我记得阈值是500M。虽然这只是为了保护目的端考虑，但是由于整个模型是pipeline，所以源端应该也能减缓。
你这个应该是本身源端内存太小导致的，可以过滤掉你说的这个大key，或者调整源端的内存。

**Comment by wwwwwwchun** [comment]
问题找到了，是因为目标端是集群办，每个节点最大为2G，我们一个key大小超过2G了。

**Comment by vinllen** [comment]
目的是集群版，写入是单节点写入吗？没有MOVED？https://github.com/alibaba/RedisShake/issues/42

**Comment by wwwwwwchun** [comment]
没有，目标端是阿里云的集群版redis，入口只有一个地址。

**Comment by vinllen** [comment]
OK，阿里云的集群版不会有问题
