### ISSUE TITLE
RedisShake集群间的实时数据同步

### ISSUE THREAD

**Issue by zolawuzhigang** [alibaba/RedisShake#491]
想咨询一下RedisShake一般做数据同步，增量实时的数据同步，最大维持时长是多久，就是在这个时间段内的集群间数据实时同步，不会遇到数据丢失，不一致类似的异常问题

**Comment by suxb201** [comment]
流量小的情况下可以一直跑下去，流量大有断连概率。与 Redis 本身的主备同步原理一样，流量大的时候 Redis 自己的主备同步也会断。

**Comment by suxb201** [comment]
见讨论：https://github.com/alibaba/RedisShake/discussions/494
