### ISSUE TITLE
在k8s中部署的二套redis集群如何做数据迁移？

### ISSUE THREAD

**Issue by zolawuzhigang** [alibaba/RedisShake#492]
如果使用redisshake怎么在二个部署在k8s中的redis集群之前做无感的数据迁移呢，因为k8s部署的redis集群对外只有一个service和端口，内部节点外部redisshake无法访问，而v3的redisshake需要连接源端的每一个master节点才能做redis集群之间的数据迁移，这种情况下应该如何解决？

**Comment by suxb201** [comment]
我认为这个每个节点的地址外部肯定是可以访问的，把这个 service 和端口写到配置文件的 target 的 address 就行。

**Comment by zolawuzhigang** [comment]
@suxb201  
![image](https://user-images.githubusercontent.com/104047841/191473418-6032eb65-7ea9-4f9e-a703-bc287c88744f.png)

**Comment by suxb201** [comment]
@zolawuzhigang 
哦，不好意思上一条说错了。
你先使用 redis-cli 连接到这个地址，然后执行 cluster nodes 命令就能看到每个 db 的地址了。然后再对这些地址使用 redis-
shake 同步。
---
不过，10.253.182.49 是什么地址？连不上说明网络就不通。

**Comment by suxb201** [comment]
现在可以用脚本直接从集群开始同步了：[快速开始：数据迁移](https://github.com/alibaba/RedisShake/wiki/%E5%BF%AB%E9%80%9F%E5%BC%80%E5%A7%8B%EF%BC%9A%E6%95%B0%E6%8D%AE%E8%BF%81%E7%A7%BB#%E9%9B%86%E7%BE%A4%E5%88%B0%E9%9B%86%E7%BE%A4c-d)
