### ISSUE TITLE
redisshake能否增加一个守护进程？

### ISSUE THREAD

**Issue by wwwwwwchun** [alibaba/RedisShake#52]
我们昨天测试的时候发现，晚上21点左右redisshake的进程断了，日志中也无报错，能否提一个技术上的需求，就是增加一个守护进程，监控redisshake的进程状态，如果进程没有了，自动把redisshake起来，类似mysqld_safe的原理。
日志如下：
2019/04/28 21:10:43 [INFO] {"PullCmdCount":3483,"PullCmdCountTotal":13225521,"BypassCmdCount":0,"BypassCmdCountTotal":0,"PushCmdCount":3483,"
PushCmdCountTotal":13225521,"SuccessCmdCount":3489,"SuccessCmdCountTotal":13225520,"FailCmdCount":0,"FailCmdCountTotal":0,"Delay":"0.09 ms","
AvgDelay":"0.80 ms","NetworkSpeed":521067,"NetworkFlowTotal":2062757702,"FullSyncProgress":100,"Status":"incr","SenderBufCount":0,"Processing
CmdCount":1,"TargetDBOffset":0,"SourceDBOffset":0}
2019/04/28 21:10:43 [INFO] sync:  +forward=3339   +nbypass=0      +nbytes=0
2019/04/28 21:10:44 [INFO] sync:  +forward=3875   +nbypass=0      +nbytes=0
2019/04/28 21:10:45 [INFO] sync:  +forward=3463   +nbypass=0      +nbytes=0
2019/04/28 21:10:46 [INFO] sync:  +forward=3656   +nbypass=0      +nbytes=0
2019/04/29 10:15:11 [WARN] 
______________________________
\                             \           _         ______ |
 \                             \        /   \___-=O'/|O'/__|
  \  redis-shake, here we go !! \_______\          / | /    )
  /                             /        '/-==__ _/__|/__=-|  -GM
 /                             /         *             \ | |
/                             /                        (o)
------------------------------

**Comment by vinllen** [comment]
感谢反馈，你说的这个应该是2个问题：
1. 退出log没打全，应该是在缓存层面最后没有刷出来
2. supervisor。 
这两个问题我们会考虑进行优化支持的。

**Comment by vinllen** [comment]
1.6.8已经添加守护进程，可以采用start.sh脚本进行启动
