### ISSUE TITLE
TLS support

### ISSUE THREAD

**Issue by ceshihao** [alibaba/RedisShake#65]
Some cloud redis versions support TLS, e.g. [ElastiCache](https://docs.aws.amazon.com/AmazonElastiCache/latest/red-ug/in-transit-encryption.html)

It looks like new version `redigo` supports TLS. 
https://github.com/gomodule/redigo

**Comment by vinllen** [comment]
Yes, this function can be improved. 
Are you interested in this [issue](https://github.com/alibaba/RedisShake/issues/42)? You can add my WeChat number `vinllen_xingge` for discussing future feature if you are convenient

**Comment by vinllen** [comment]
Hi, @ceshihao could u plz also add SSL support because of some Redis version using SSL protocol? BTW, I can give you an aliyun Redis version with SSL support to be tested.

**Comment by vinllen** [comment]
BTW, do you have any idea that how can I test your TLS support code?

**Comment by ceshihao** [comment]
@vinllen 
1. I am not sure which `SSL` version you use.
However, `SSL` is a predecessor of `TLS`.  [`crypto/tls`](https://golang.org/pkg/crypto/tls/) partially implements TLS 1.2, and TLS 1.3.
In most cases, `SSL` means `TLS` for convention. 

2. I test the codes based on AWS ElastiCache with `TLS` enable.
I think it is easy for you to find a free node to test.
