### ISSUE TITLE
RedisTypeCluster 模式下，优化地址填写一个即可

### ISSUE THREAD

**Issue by zhklcf** [alibaba/RedisShake#70]
对于源端是 cluster类型的，比如说有30个node,也要填30个地址？
是否可以考虑，填写1个地址，然后通过 cluster nodes命令获取集群拓扑信息，这样用户不用填30个地址了~

**Comment by vinllen** [comment]
v1.6.3版本已经支持，https://github.com/alibaba/RedisShake/pull/77
以@开头支持节点探测，具体使用请参考https://github.com/alibaba/RedisShake/wiki/%E7%AC%AC%E4%B8%80%E6%AC%A1%E4%BD%BF%E7%94%A8%EF%BC%8C%E5%A6%82%E4%BD%95%E8%BF%9B%E8%A1%8C%E9%85%8D%E7%BD%AE%EF%BC%9F
