### ISSUE TITLE
redis 4.0 cluster 同步到 redis 3.2.9 主从结构

### ISSUE THREAD

**Issue by fanlifei** [alibaba/RedisShake#76]
程序没有使用4.0相关的命令，都是基础命令。
报错如下：
2019/05/21 16:20:01 [PANIC] target key name is busy:%!(EXTRA string=<C6>-<CD>^P<9C>K<BE><D1>~m)
[stack]: 
    1   /home/zhuzhao.cx/redis-shake/src/redis-shake/common/utils.go:756
            redis-shake/common.RestoreRdbEntry
    0   /home/zhuzhao.cx/redis-shake/src/redis-shake/sync.go:435
            redis-shake.(*dbSyncer).syncRDBFile.func1.1
        ... ...

**Comment by vinllen** [comment]
这个错是目的端key已经存在了，要么删除对应的key同步，要么启用rewrite参数
https://github.com/alibaba/RedisShake/wiki/FAQ#q-how-to-solve-the-target-key-name-is-busy-error
