### ISSUE TITLE
Prometheus Metrics Support

### ISSUE THREAD

**Issue by ceshihao** [alibaba/RedisShake#81]
Current `/metric` API response is like json format. e.g.
```
[{"StartTime":"2019-05-28T07:22:43Z","PullCmdCount":0,"PullCmdCountTotal":69,
"BypassCmdCount":0,"BypassCmdCountTotal":0,"PushCmdCount":0,
"PushCmdCountTotal":69,"SuccessCmdCount":1,"SuccessCmdCountTotal":69,
"FailCmdCount":0,"FailCmdCountTotal":0,"Delay":"268.00 ms","AvgDelay":"284.99 ms",
"NetworkSpeed":0,"NetworkFlowTotal":6607,"FullSyncProgress":100,"Status":"incr",
"SenderBufCount":0,"ProcessingCmdCount":0,"TargetDBOffset":136104580201,
"SourceDBOffset":136104587992,"SourceAddress":"redis_src_address:6379",
"TargetAddress":["redis_target_address:6379"]}]
```

It is appreciated if it supports Prometheus text-based format.
https://prometheus.io/docs/instrumenting/exposition_formats/

It is better to add a `/metrics` API in order to not break any existing function.

**Comment by vinllen** [comment]
This is a good suggestion, supporting Prometheus API can make makes it easy for our tools to connect to the monitoring end.
This can be our future feature.

**Comment by ceshihao** [comment]
Good to hear that.
